// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xezcxjahufdbbyolelyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlemN4amFodWZkYmJ5b2xlbHl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTA5NDEsImV4cCI6MjA3MDE2Njk0MX0.v0ZmEYevqE-WB1r1AvX4Qfcy8NuNZ6uRYTsAf03ry54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});